Algoritmo "Problema_pagamento"

Var

   nome : caractere
   valorPorhora, horaQuant, valorFinal : real

Inicio

   escreva("Nome: ")
   leia(nome)
   escreva("Valor por hora: ")
   leia(valorPorHora)
   escreva("Quantidade de hora: ")
   leia(horaQuant)
   
   // CALC
   valorFinal <- valorPorHora * HoraQuant
   escreva("O pagamento para ser efetuado para ", nomeFuncionaria, " é de R$ ", valorFinal:1:2)
   



Fimalgoritmo